# Generated by Django 3.2.5 on 2023-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('U', 'Moving Up'), ('D', 'Moving Down'), ('S', 'Stopped'), ('M', 'Maintenance')], default='S', max_length=1)),
                ('door', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='C', max_length=1)),
                ('current_floor', models.IntegerField(default=0)),
                ('destination_floor', models.IntegerField(blank=True, null=True)),
                ('requests', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
